version: '1'

services:
  qiyu-live-user-provider-docker-1:
    container_name: live-user-provider-docker-1
    image: 'live-user-provider-docker:1.0-SNAPSHOT'
    ports:
      - "9091:9091"
    volumes:
      - /c/Java/logs:/tmp/logs/live-user-provider
    environment:
      - DUBBO_IP_TO_REGISTRY=192.168.0.103
      - DUBBO_PORT_TO_REGISTRY=9091
      - DUBBO_PORT_TO_BIND=9091
      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms512m -Xmx512m -Xmn128m -Xss256k
    extra_hosts:
      - 'hang.nacos.com:host-gateway'
      - 'hang.db:47.95.42.71'
      - 'hang.rmq.com:host-gateway'
      - 'hang.redis:47.95.42.71'

  qiyu-live-user-provider-docker-2:
    container_name: live-user-provider-docker-2
    image: 'live-user-provider-docker:1.0-SNAPSHOT'
    ports:
      - "9092:9092"
    volumes:
      - /c/Java/logs:/tmp/logs/hang-live-user-provider
    environment:
      - DUBBO_IP_TO_REGISTRY=192.168.0.103
      - DUBBO_PORT_TO_REGISTRY=9092
      - DUBBO_PORT_TO_BIND=9092
      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms512m -Xmx512m -Xmn128m -Xss256k
    extra_hosts:
      - 'hang.nacos.com:host-gateway'
      - 'hang.db:47.95.42.71'
      - 'hang.rmq.com:host-gateway'
      - 'hang.redis:47.95.42.71'