version: '1'

services:
  live-user-provider-8089:
    container_name: live-user-provider-8089
    image: 'live-user-provider-docker:1.0-SNAPSHOT'
    ports:
      - "9089:9089"
    volumes:
      - /c/Java/logs:/tmp/logs/live-user-provider
    environment:
      - DUBBO_IP_TO_REGISTRY=192.168.0.102
      - DUBBO_PORT_TO_REGISTRY=9089
      - DUBBO_PORT_TO_BIND=9089
      - JAVA_OPTS=-XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=128m -Xms64m -Xmx128m -Xmn64m -Xss4m
    extra_hosts:
      - 'hang.nacos.com:47.95.42.71'
      - 'hang.rmq.com:47.95.42.71'
