version: '3'
services:
  live-api-controller-9098:
    container_name: live-api-controller-9098
    image: 'live-api-controller-docker:1.0-SNAPSHOT'
    ports:
      - "9098:9098"
    volumes:
      - /c/Java/logs:/tmp/logs/live-api-controller
    environment:
      - spring.cloud.nacos.discovery.ip=192.168.0.102 #Make sure this service is registered in host address rather than container address.
      - server.port=9098
      - JAVA_OPTS=-DNACOS_USER=hang -DNACOS_PWD=ZH131314 -XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=172m -Xms64m -Xmx128m -Xmn64m -Xss512k

#
#  live-api-2:
#    container_name: live-api-docker-2
#    image: 'live-api-docker:1.0-SNAPSHOT'
#    ports:
#      - "8082:8082"
#    volumes:
#      - /c/Java/logs:/tmp/logs/live-api
#    environment:
#      - spring.cloud.nacos.discovery.ip=192.168.0.103
#      - server.port=8082
#      - JAVA_OPTS=-DNACOS_USER=hang -DNACOS_PWD=ZH131314 -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms512m -Xmx512m -Xmn128m -Xss256k
#    extra_hosts:
#      - 'hang.nacos.com:host-gateway'
